In [5]:
import pandas as pd
import epiweeks

In [6]:
raw_gender_df = pd.read_csv('raw_gender_data.csv')

In [7]:
raw_gender_df

,location,date,cases_total,male_cases,female_cases,percent_male_cases,percent_female_cases,male_case_rate,female_case_rate,deaths_total,male_deaths,female_deaths,percent_male_deaths,percent_female_deaths,male_death_rate,female_death_rate
0,"<td class=""s11"">Alabama</td>","<td class=""s12"" dir=""ltr"">4/13</td>","<td class=""s12"">4,572</td>","<td class=""s12"">1876</td>","<td class=""s12"">2615</td>","<td class=""s12"">41.03</td>","<td class=""s12"">57.20</td>","<td class=""s12"" dir=""ltr"">79.63</td>","<td class=""s12"" dir=""ltr"">104.24</td>","<td class=""s12"">96</td>","<td class=""s12"" dir=""ltr"">56</td>","<td class=""s12"" dir=""ltr"">40</td>","<td class=""s12"" dir=""ltr"">58.80</td>","<td class=""s12"" dir=""ltr"">41.20</td>","<td class=""s12"" dir=""ltr"">2.36</td>","<td class=""s13"" dir=""ltr"">1.58</td>"
1,"<td class=""s11"">Alaska</td>","<td class=""s12"" dir=""ltr"">4/13</td>","<td class=""s12"">272</td>","<td class=""s12"">134</td>","<td class=""s12"">138</td>","<td class=""s12"">49.30</td>","<td class=""s12"">50.70</td>","<td class=""s12"" dir=""ltr"">34.78</td>","<td class=""s12"" dir=""ltr"">39.07</td>","<td class=""s12"">8</td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s12"" dir=""ltr"">0.00</td>","<td class=""s12"" dir=""ltr"">0.00</td>"
2,"<td class=""s11"">Arizona</td>","<td class=""s12"" dir=""ltr"">4/13</td>","<td class=""s12"">3539</td>","<td class=""s12"">1663</td>","<td class=""s12"">1876</td>","<td class=""s12"">47.00</td>","<td class=""s12"">53.00</td>","<td class=""s12"" dir=""ltr"">48.16</td>","<td class=""s12"" dir=""ltr"">53.69</td>","<td class=""s12"">169</td>","<td class=""s12"" dir=""ltr"">100</td>","<td class=""s12"" dir=""ltr"">69</td>","<td class=""s12"" dir=""ltr"">59.00</td>","<td class=""s12"" dir=""ltr"">41.00</td>","<td class=""s12"" dir=""ltr"">2.89</td>","<td class=""s13"" dir=""ltr"">1.98</td>"
3,"<td class=""s11"">Arkansas</td>","<td class=""s12"" dir=""ltr"">4/13</td>","<td class=""s12"">1280</td>","<td class=""s12"">552</td>","<td class=""s12"">728</td>","<td class=""s12"">43.10</td>","<td class=""s12"">56.90</td>","<td class=""s12"" dir=""ltr"">37.57</td>","<td class=""s12"" dir=""ltr"">47.84</td>","<td class=""s12"">27</td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s12"" dir=""ltr"">0.00</td>","<td class=""s13"" dir=""ltr"">0.00</td>"
4,"<td class=""s11"">California </td>","<td class=""s12"" dir=""ltr"">4/13</td>","<td class=""s22"">21,794</td>","<td class=""s12"">10926</td>","<td class=""s12"">10571</td>","<td class=""s12"">50.13</td>","<td class=""s12"">48.50</td>","<td class=""s12"" dir=""ltr"">56.16</td>","<td class=""s12"" dir=""ltr"">53.67</td>","<td class=""s12"">651</td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s12"" dir=""ltr"">0.00</td>","<td class=""s13"" dir=""ltr"">0.00</td>"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,"<td class=""s11"">Virginia</td>","<td class=""s12"" dir=""ltr"">4/27</td>","<td class=""s12"" dir=""ltr"">12970</td>","<td class=""s12"" dir=""ltr"">6168</td>","<td class=""s12"" dir=""ltr"">6708</td>","<td class=""s12"">47.56</td>","<td class=""s12"">51.72</td>","<td class=""s12"" dir=""ltr"">149.04</td>","<td class=""s12"" dir=""ltr"">156.90</td>","<td class=""s12"" dir=""ltr"">448</td>","<td class=""s12"" dir=""ltr"">241</td>","<td class=""s12"" dir=""ltr"">203</td>","<td class=""s12"">53.79</td>","<td class=""s12"">45.31</td>","<td class=""s12"" dir=""ltr"">5.82</td>","<td class=""s12"" dir=""ltr"">4.75</td>"
102,"<td class=""s11"">Washington</td>","<td class=""s12"" dir=""ltr"">4/27</td>","<td class=""s12"" dir=""ltr"">13521</td>","<td class=""s12"">6220</td>","<td class=""s12"">7031</td>","<td class=""s12"" dir=""ltr"">46.00</td>","<td class=""s12"">52.00</td>","<td class=""s12"" dir=""ltr"">170.60</td>","<td class=""s12"" dir=""ltr"">192.70</td>","<td class=""s12"" dir=""ltr"">749</td>","<td class=""s12"">419</td>","<td class=""s12"">322</td>","<td class=""s12"" dir=""ltr"">56.00</td>","<td class=""s12"">43.00</td>","<td class=""s12"" dir=""ltr"">11.51</td>","<td class=""s12"" dir=""ltr"">8.83</td>"
103,"<td class=""s11"">West Virginia</td>","<td class=""s12"" dir=""ltr"">4/27</td>","<td class=""s12"" dir=""ltr"">1053</td>","<td class=""s12"">424</td>","<td class=""s12"">625</td>","<td class=""s12"">40.30</td>","<td class=""s12"" dir=""ltr"">59.40</td>","<td class=""s12"" dir=""ltr"">46.93</td>","<td class=""s12"" dir=""ltr"">67.63</td>","<td class=""s12"" dir=""ltr"">34</td>","<td class=""s12""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s12""></td>","<td class=""s12"" dir=""ltr"">0.00</td>","<td class=""s12"" dir=""ltr"">0.00</td>"
104,"<td class=""s11"">Wisconsin</td>","<td class=""s12"" dir=""ltr"">4/27</td>","<td class=""s12"" dir=""ltr"">5911</td>","<td class=""s12"">2837</td>","<td class=""s12"">3074</td>","<td class=""s12"" dir=""ltr"">48.00</td>","<td class=""s12"" dir=""ltr"">52.00</td>","<td class=""s12"" dir=""ltr"">98.78</td>","<td class=""s12"" dir=""ltr"">105.77</td>","<td class=""s12"" dir=""ltr"">272</td>","<td class=""s12"">160</td>","<td class=""s12"">112</td>","<td class=""s12"" dir=""ltr"">59.00</td>","<td class=""s12"" dir=""ltr"">41.00</td>","<td class=""s12"" dir=""ltr"">5.59</td>","<td class=""s12"" dir=""ltr"">3.84</td>"
105,"<td class=""s11"">Wyoming</td>","<td class=""s12"" dir=""ltr"">4/27</td>","<td class=""s12"" dir=""ltr"">370</td>","<td class=""s12"">181</td>","<td class=""s12"">181</td>","<td class=""s12"" dir=""ltr"">48.90</td>","<td class=""s12"" dir=""ltr"">48.90</td>","<td class=""s12"" dir=""ltr"">60.92</td>","<td class=""s12"" dir=""ltr"">63.52</td>","<td class=""s12"" dir=""ltr"">7</td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s11""></td>","<td class=""s12"" dir=""ltr"">0.00</td>","<td class=""s12"" dir=""ltr"">0.00</td>"